0.7.3

diff --git a/swbb b/swbb
--- a/swbb
+++ b/swbb
@@ -1,11 +1,11 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 
 #Simple Wine Building Bot -- swbb
 #	automatic wine, wine-staging, wine-pba, wine-pba-firerat download, patch, build, install script
 #	build with 64bit wine
 
-swbb_version=0.7.2
+SWBB_VERSION=0.7.3
 
 #fedora:
 #	sudo dnf group install install samba-winbind-clients
@@ -21,16 +21,16 @@ swbb_version=0.7.2
 # build setting  MODIFY ME!
 build_thread=8													# CPU logical core +1 for max speed and max cpu usage
 build_mode='interactive'										# [ interactive, automatic ]
-check_update='no'												# [ yes, no ] check source update or skip
-product='wine-pba'													# [ wine, wine-staging, wine-pba, wine-stagingpba-firerat, wine-pba-firerat ] Also use as dir name for source and built binary. wine-stagingpba-firerat: `staging with pba` by firerat. wine-pba-firerat: Use pba patch by firerat on official staging
+check_update='yes'												# [ yes, no ] check source update or skip
+product='wine-staging'											# [ wine, wine-staging, wine-pba, wine-stagingpba-firerat, wine-pba-firerat ] Also use as dir name for source and built binary. wine-stagingpba-firerat: `staging with pba` by firerat. wine-pba-firerat: Use pba patch by firerat on official staging
 selector='tag'													# [ tag, commit ] default: tag ; use commit to build minor release like staging 3.13.1 or build with esync
-version='3.7'												# ignored when selector set to 'commit', official announced version like 3.15
+version='4.0'													# ignored when selector set to 'commit', official announced version like 3.15
 wine_commit='3056f9beb95f66e598ab51d5d37b21a548b3e5f8'			# ignored when selector set to 'tag'
 staging_commit='214a0fd7bd45e431f548f1d7974b3f24410dd9d8'		# ignored when selector set to 'tag', match wine_commit
 stagingpba_firerat_commit=''									# https://gitlab.com/Firer4t/wine-staging
 pba_firerat_commit=''
 
-optimize_native_cpu=1 											# pass CFLAGS, CXXFLAGS to configure, optimize for your native cpu, but your build will not run on other cpus!
+optimize_native_cpu=0 											# pass CFLAGS, CXXFLAGS to configure, optimize for your native cpu, but your build will not run on other cpus!
 
 # Custom patches setting
 patch_wine=0											# [0,1] 0: do not use custom patches for wine; 1:use custom patches for wine
@@ -49,7 +49,7 @@ configure_32args='--disable-tests --disable-win16 --with-wine64=../64build --wit
 
 # swbb setting
 git_dir="$HOME/_wine_git"
-build_ts="$(date '+%y-%m-%d-%H-%M')"
+build_ts="$( date '+%y-%m-%d-%H-%M' )"
 if [ X"$selector" == X'tag' ]; then
 	dir_name="$product-$version"
 elif [ X"$selector" == X'commit' ]; then
@@ -67,19 +67,19 @@ elif [ X"$selector" == X'commit' ]; then
 		dir_name="$product-$pba_firerat_commit"
 		;;
 	*)
-		printf 'wrong value in $product'
+		printf "wrong value in \$product"
 		exit 1
 		;;
 	esac
 else
-	printf 'wrong value in $selector'
+	printf "wrong value in \$selector"
 	exit 1
 fi
 
 # append cpu_march string to built dir name
-if (( $optimize_native_cpu == 1 )); then
-	cpu_march="$(gcc -v -E -x c /dev/null -o /dev/null -march=native 2>&1 | grep /cc1 | tr " " "\n" | grep -e "-march" | sed -n -E 's/-march=//gp')"
-	[ -z cpu_march ] && cpu_march="cpu-march-unknown"
+if (( optimize_native_cpu == 1 )); then
+	cpu_march="$( gcc -v -E -x c /dev/null -o /dev/null -march=native 2>&1 | grep /cc1 | tr " " "\n" | grep -e "-march" | sed -En 's/-march=//gp' )"
+	[ -z "$cpu_march" ] && cpu_march="cpu-march-unknown"
 	dir_name="$dir_name"-"$cpu_march"
 else
 	:
@@ -95,14 +95,14 @@ install_dir="$HOME/__wine_install/$build_ts/$dir_name"			# built wine binary her
 swbb_pause()
 {
 	if [ X"$build_mode" == X'interactive' ]; then
-		read -p 'Press Ctrl+C to terminate, Press any key to continue.' pause_input
-		unset pause_input
+		read -r -p 'Press Ctrl+C to terminate, Press any key to continue.' temp_var
+		unset temp_var
 	fi
 }
 
 swbb_error()
 {
-	echo "$(basename $0) [ERROR]: $1" >&2
+	printf "swbb ERROR: %s\n" "$*" >&2
 	exit 1
 }
 
@@ -110,13 +110,13 @@ swbb_check_dependencies()
 {
 	dependencies=(ccache git sudo)
 	missing=0
-	for ((i=0; i < ${#dependencies[*]}; i++)); do
-		if ! (which ${dependencies[i]} >/dev/null 2>&1); then
+	for (( i=0; i < ${#dependencies[*]}; i++ )); do
+		if ! ( command -v "${dependencies[i]}" >/dev/null ); then
 			echo "${dependencies[i]}" not found.
-			missing=$(($missing+1))
+			missing=$(( missing+1 ))
 		fi
 	done
-	if (( $missing > 0 )); then
+	if (( missing > 0 )); then
 		swbb_error "$missing" dependencies not found.
 	fi
 }
@@ -182,7 +182,7 @@ swbb_prepare()
 			;;
 		esac
 		;;
-	wine-stagingpba-firerat )
+	wine-stagingpba-firerat)
 		url='https://gitlab.com/Firer4t/wine-staging.git'
 		git_archive='yes'
 		if [ X"$selector" == X'tag' ]; then
@@ -211,15 +211,15 @@ swbb_prepare()
 
 	if [ -d ./"$local"/.git ]; then
 		cd ./"$local"
-		if [ X"$check_update" == X'yes' ];then
-			printf "Check %s update...\n" $remote
+		if [ X"$check_update" == X'yes' ]; then
+			printf "Check %s update...\n" "$remote"
 			git fetch
 			git pull
 		else
-			printf "%s update skipped.\n" $remote
+			printf "%s update skipped.\n" "$remote"
 		fi
 	else
-		if [ X"$check_update" == X'yes' ];then
+		if [ X"$check_update" == X'yes' ]; then
 			git clone "$url" "$local"
 			cd ./"$local"
 		else
@@ -228,11 +228,11 @@ swbb_prepare()
 	fi
 
 	if [ X"$git_archive" == X'yes' ]; then
-		if ! (git show "$release" 1>/dev/null); then
+		if ! ( git show "$release" 1>/dev/null ); then
 			swbb_error 'wrong wine tag or commit hash'
 		fi
 		mkdir -p "$build_dir/$local"
-		git archive --format=tar "$release" | (cd "$build_dir/$local" && tar xf -)
+		git archive --format=tar "$release" | ( cd "$build_dir/$local" && tar xf - )
 	elif [ X"$git_archive" == X'no' ]; then
 		cp -R "$git_dir/$local" "$build_dir"
 	else
@@ -245,7 +245,7 @@ swbb_patch()
 {
 	cd "$build_dir/wine"
 	patch_dir="$1"
-	readarray -t arpf <<< $( ls -1 "$patch_dir" )
+	readarray -t arpf<<<"$( ls -1 "$patch_dir" )"
 	for (( i=0; i < ${#arpf[@]}; i++ )); do
 		if ( git apply "$patch_dir/${arpf[i]}" ); then
 			echo "Applied patch: $patch_dir/${arpf[i]}"
@@ -259,9 +259,11 @@ swbb_patch()
 
 #### main()
 ##{
-printf "Simple Wine Building Bot %s\n\n" $swbb_version
+printf "Simple Wine Building Bot %s\n\n" $SWBB_VERSION
+printf "current wine build option:\n%s\n\n" "$configure_32args"
+printf "current wine64 build option:\n%s\n\n" "$configure_64args"
 printf "Check configure section carefully before run.\n\n"
-printf "Ready to build %s?\n" $dir_name
+printf "Ready to build %s?\n\n" $dir_name
 swbb_pause
 swbb_check_dependencies
 
@@ -300,7 +302,7 @@ esac
 swbb_pause
 
 #  Apply custom patch for wine
-if (( $patch_wine == 1 )); then
+if (( patch_wine == 1 )); then
 	swbb_patch "$wine_patch_dir"
 	echo 'DONE: Apply custom patch for wine'
 	swbb_pause
@@ -312,7 +314,7 @@ if [ X"$product" == X'wine-staging' ] || [ X"$product" == X'wine-pba' ] || [ X"$
 	./patchinstall.sh DESTDIR="$build_dir/wine" --all
 	echo 'DONE: Use staging'
 	swbb_pause
-	if (( $patch_staging == 1 )); then
+	if (( patch_staging == 1 )); then
 		swbb_patch "$staging_patch_dir"
 		echo 'DONE: Apply custom patch for staging'
 		swbb_pause
@@ -332,7 +334,7 @@ if [ X"$product" == X'wine-pba' ]; then
 	swbb_patch "$build_dir/wine-pba/patches"
 	echo 'DONE: Use pba'
 	swbb_pause
-	if (( $patch_pba == 1 )); then
+	if (( patch_pba == 1 )); then
 		swbb_patch "$pba_patch_dir"
 		echo 'DONE: Apply custom patch for pba'
 		swbb_pause
@@ -344,7 +346,7 @@ if [ X"$product" == X'wine-pba-firerat' ]; then
 	swbb_patch "$build_dir/wine-pba-firerat/patches"
 	echo 'DONE: Use pba-firerat'
 	swbb_pause
-	if (( $patch_pba_firerat == 1 )); then
+	if (( patch_pba_firerat == 1 )); then
 		swbb_patch "$pba_firerat_patch_dir"
 		echo 'DONE: Apply custom patch for pba-firerat'
 		swbb_pause
@@ -355,7 +357,7 @@ fi
 cd "$build_dir/wine"
 mkdir -p 64build && cd 64build
 
-if (( $optimize_native_cpu == 1 )); then
+if (( optimize_native_cpu == 1 )); then
 	echo "$configure_64args --prefix=$install_dir CFLAGS='-march=native -O2' CXXFLAGS='-march=native -O2' CC='ccache gcc'" | xargs ../configure
 else
 	echo "$configure_64args --prefix=$install_dir CFLAGS='-O2' CXXFLAGS='-O2' CC='ccache gcc'" | xargs ../configure
@@ -367,7 +369,7 @@ swbb_pause
 cd "$build_dir/wine"
 mkdir -p 32build && cd 32build
 
-if (( $optimize_native_cpu == 1 )); then
+if (( optimize_native_cpu == 1 )); then
 	echo "$configure_32args --prefix=$install_dir CFLAGS='-march=native -O2' CXXFLAGS='-march=native -O2' CC='ccache gcc'" | xargs ../configure
 else
 	PKG_CONFIG_PATH=/usr/lib echo "$configure_32args --prefix=$install_dir CFLAGS='-O2' CXXFLAGS='-O2' CC='ccache gcc'" | xargs ../configure
@@ -377,10 +379,10 @@ echo 'DONE: 32bit configure. Ready to build?'
 swbb_pause
 
 # make
-time1=$(date '+%T')
+time1=$( date '+%T' )
 cd "$build_dir/wine/64build" && make "-j$build_thread"
 cd "$build_dir/wine/32build" && make "-j$build_thread"
-time2=$(date '+%T')
+time2=$( date '+%T' )
 
 # install, need sudo
 cd "$build_dir/wine/64build"
@@ -390,7 +392,7 @@ cd "$build_dir/wine/32build"
 #sudo make install
 sudo make install-lib
 echo 'Install needs sudo, which result wine files owned by root, now chown to you...'
-sudo chown -hR $(whoami) "$install_dir"
+sudo chown -hR "$( whoami )" "$install_dir"
 echo "compile start: $time1"
 echo "compile end:   $time2"
 ##}
